publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJ1Oz87vmn1tsjH6KwPQMduIBlXP6MWLvPa+CdGH0znpM95bQc9hwLKyjz5wm+8d0OnETz7ms2B0H1QfGCcVACcCAwEAAQ==
# 应用名称
spring:
  application:
    name: xmall-server
  output:
    ansi:
      enabled: always
  thymeleaf:
    cache: false
#允许用户自定义的类覆盖系统提供的类
  main:
    allow-bean-definition-overriding: true
#静态文件请求匹配方式（只要请求路径匹配到了，就访问下面配置的默认静态资源路径）
  mvc:
    static-path-pattern: /static/*,/upload/*
#数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/xmall?characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: PsV1vvdTYMXmcE1KCLO24FGAhs08SH48XW6O2J9RLssoZDAYoadTzO95O+For8G746nRVP2U4UItshbmO+F47A==
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      filters: config,stat,slf4j
      filter:
        config:
          enabled: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true;config.decrypt.key=${publicKey}



management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,shutdown
server:
  port: 8080
logging:
  #这种方法是使用xml的配置文件的形式配置，该xml配置文件规定了日志的格式，级别等信息
  config: classpath:logback.xml
  level:
    com.xdx.xmall: trace


